## PROFILE DEV

server:
  servlet:
    context-path: /vw/api
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  port: 3000
  ssl:
    enabled: true
    key-store: "C:\\certificate\\srv-keystore.p12"
    key-store-password: "secret"
    key-store-type: "PKCS12"
    client-auth: want
    trust-store: "C:\\certificate\\srv-truststore.p12"
    trust-store-password: "secret"
    trust-store-type: "PKCS12"
    protocol: "TLS"
    enabled-protocols: TLSv1.2, TLSv1.3
spring:
  application:
    name: virtual-wallet

  datasource:
    url: jdbc:mysql://localhost:3306/vw
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

springdoc:
  default-produces-media-type: application/json

application:
  mailing:
    email: caitocd@gmail.com
    email-pass: cknldtamtqvslhlg
    frontend:
      activation-url: http://localhost:4200/activate-account